### ISSUE TITLE
Draw dashed arrow on confounder_triangle

### ISSUE THREAD

**Issue by floswald** [cran/ggdag#1]
Hi there

I was trying to get the two arrows starting from z to be linetype dashed in confounder_triangle(), but couldn’t figure out how - also trying to directly ggplot this. Any ideas how I could achieve that? 

Thanks for the great package.

**Comment by gaborcsardi** [comment]
Hi, thanks! This is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!
